name: api-uber
region: fra

# Services backend (API FastAPI)
services:
  - name: backend
    github:
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
      branch: main
      deploy_on_push: true
    dockerfile_path: ./backend/Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
      initial_delay_seconds: 60
      period_seconds: 10
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 5
    envs:
      - key: APP_ENV
        value: prod
      - key: SKIP_STARTUP_SYNC
        value: "true"
      - key: DB_HOST
        scope: RUN_TIME
        type: SECRET
      - key: DB_PORT
        scope: RUN_TIME
        type: SECRET
      - key: DB_NAME
        scope: RUN_TIME
        type: SECRET
      - key: DB_USER
        scope: RUN_TIME
        type: SECRET
      - key: DB_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: PYTHONUNBUFFERED
        value: "1"
    routes:
      - path: /api

  - name: frontend
    github:
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
      branch: main
      deploy_on_push: true
    dockerfile_path: ./frontend/Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: VITE_API_BASE_URL
        scope: BUILD_TIME
        # Utiliser la variable d'environnement définie dans Digital Ocean App-Level
        # Si définie dans App-Level Environment Variables, elle sera utilisée
        # Sinon, utiliser ${backend.PUBLIC_URL}/api comme fallback
        value: ${backend.PUBLIC_URL}/api
    routes:
      - path: /

# Base de données PostgreSQL (optionnel si vous utilisez Supabase)
# Si vous utilisez Supabase, commentez cette section
# databases:
#   - name: db
#     engine: PG
#     version: "15"
#     production: true
#     cluster_name: db-cluster

